#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Midterm Question #1

"""
import numpy as np 
import matplotlib.pyplot as plt

x = T  #defining the x 
y = L   #defining y 
t = np.linspace(0, 10, 1001)   #creating an array for our min and max 

y = omega*x**beta   #Inputting the equation 
from star_luminous.txt as star

plt(x, y)    #creating a plot 
plt.xlabel(0, 1001, 10)
plt.ylabel()
plt.show()

