#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Midterm Question #2

"""
"""
#A
import numpy as np 
import matplotlib.pyplot as plt 
x = linspace(-10, 9, 2)   #creating an array for the interval
y = x**5 +2/5*x**2 -2 #inputting th equation 

i = 0            #creating a while loop w a true/false statement 
while y[i] >= 0:
    i += 1     #now y[i-1]>0 and y[i]<0 therefore finding the middle point
    print "y = 0 dt", (y)
"""
"""
#B
import numpy as np 
import matplotlib.pyplot as plt 
y = **-x/10 + x #inputting the equation 
"""
#C
import numpy as np
import maplotlib.pyplot as plt 
from math import sine
N = 50
x = linspace.py(-10. 9, 2)
y = 10*sine(x/4) + 0.1*(x + 12)
plt.plot(x, y, 'g__')
plt.xlabel( N)
plt.ylabel( y <= 0)
plt.show()

    